services:
  spyserver:
    container_name: spyserver
    image: nikotine1/spyserver:latest
    restart: unless-stopped
    privileged: true
    environment:
      - LIST_IN_DIRECTORY=0
      - DEVICE_TYPE=RTL-SDR
      - DEVICE_SERIAL=0
      - BIND_PORT=5555
    ports:
      - "5555:5555"